### ISSUE TITLE
MaskedFormatter.getMaskLength() is null

### ISSUE THREAD

**Issue by yura-f** [VicMikhailau/MaskedEditText#9]
Once again, when I began to enter the first character in the text box, caught the bug:
```
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.lifemarket.lifeclub, PID: 1262
                  java.lang.NullPointerException: Attempt to invoke virtual method 'int com.vicmikhailau.maskededittext.MaskedFormatter.getMaskLength()' on a null object reference
                      at com.vicmikhailau.maskededittext.MaskedWatcher.afterTextChanged(MaskedWatcher.java:41)
                      at android.widget.TextView.sendAfterTextChanged(TextView.java:8004)
                      at android.widget.TextView$ChangeWatcher.afterTextChanged(TextView.java:10165)
                      at android.text.SpannableStringBuilder.sendAfterTextChanged(SpannableStringBuilder.java:1043)
                      at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:560)
                      at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:492)
                      at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:491)
                      at android.text.method.NumberKeyListener.onKeyDown(NumberKeyListener.java:121)
```

Mask format like this:
```
MaskedFormatter formatter = new MaskedFormatter("+#(###)###-##-##");
editText.addTextChangedListener(new MaskedWatcher(formatter, editText));
```

**Comment by Mixser** [comment]
@Z-13 It's because we use weak ref to `formatter` in watcher. So you must make formatter as class member. Sorry about it, forget change docs.

**Comment by yura-f** [comment]
@Mixser ok! thx
